### ISSUE TITLE
BUG: Cannot pay via PayPal link/button

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#170]
Hashers trying to pay for tonight's SeaMon H3 trail get this error message. The URL listed in our kennel settings is correct, so this is likely on the app side of things.

![252846713_1040563740115690_5439879090201939768_n](https://user-images.githubusercontent.com/49632769/140840625-06dddead-ee06-4944-8bc7-ab78e9852799.jpg)

**Comment by diabWH3** [comment]
Same goes with clicking the "Visit Event on Facebook" link at the bottom of a FB-sourced event.
An error message pops up saying:
"Unable to open link

Harrier Central was unable to open <url>"

**Comment by diabWH3** [comment]
And the clickable map icon does not forward to my mobile device's map service (Google Maps). The app seems to be unable to handle all external URLs at the moment.

**Comment by James-A-White** [comment]
Thanks... will check.  I'm going to try a small PayPal payment to you and see if that works.

**Comment by James-A-White** [comment]
It seems to be working on iOS which is where I do most of my testing, I’ll load it up on my android and see if I can reproduce the problem there.

**Comment by James-A-White** [comment]
Hey DIAB, I've tested this on two Android devices and it worked on both. What I did notice, however, when we were at the Zombie run this weekend and had poor internet connection is that the links were not working when there was no network connection, but I was not returning a valid error message about "no network". Since this problem affected many people at the same time, is it possible that you were in an area with poor network reception?  Could you test this again for me in a place where you know the network is good?  If it is still broken, I'll need to get your Android version and device and set up a simulator for that combination and give it a test.

In the meantime, I'm going to "wrap" those connection requests with some enhanced error handling to better handle cases where either there is no network connection at all or the network connection is slow.

Many thanks!

p.s. (not related to this error), I'm making some excellent progress on displaying Harrier Central run information on normal websites.  Our aim is to make it easy for Kennels to replace their existing web content with data pulled from our database which will make it super easy to ensure that run information is kept in sync across Facebook, the App and Kennel websites. Will keep you posted on progress.

**Comment by diabWH3** [comment]
The errors experienced last week are persistent and the attached screenshot
is from just now, done from my home with decent cell signal and connected
to WiFi. Multiple users, scattered all around the geographical region and
using a variety of mobile devices, reported the same error.

Nothing has changed on our kennel's admin side of things, so hopefully you
can track down this issue!

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by James-A-White** [comment]
OK, that's helpful. I'll run it in the simulator tonight when I get home and see if I can track it down. You might end up getting a payment from me... if you do, please keep it and buy yourself a beer or two as a thank you for all you've done to help test!

**Comment by James-A-White** [comment]
I've tested with the latest version of HC and it's working. Can you download 1.0.35 and give it a spin? I noticed some strange behavior not related to this regarding map pins on the last release. I didn't change any code and it seems fixed now. I'm wondering if there was a problem in the Flutter version I was using at the time that has since been fixed?

I'm going to test now on Android to see if it's working there as well.

![IMG_205649791CC0-1](https://user-images.githubusercontent.com/5836474/142862103-29606969-84e5-4f86-9de6-093706df798c.jpeg)
![IMG_84A2C4ECCF8B-1](https://user-images.githubusercontent.com/5836474/142862121-ccc7c0db-1bad-4bf5-82eb-dd50843a09d4.jpeg)

**Comment by diabWH3** [comment]
This issue is still prevalent in Android version 1.0.36. Users still cannot
execute buttons with external URIs:
- PayPal payment button
- Map pin directing to Google Maps
- "Visit Event on Facebook" button

**Comment by diabWH3** [comment]
Screenshots showing non-functioning external links. The Facebook button throws an error message, but clicking the map pin doesn't do anything.

![Screenshot_20211130-092718](https://user-images.githubusercontent.com/49632769/144097459-6c7b9225-e796-454b-8647-f7ca994511cc.png)

![Screenshot_20211130-092745](https://user-images.githubusercontent.com/49632769/144097471-803baf27-cfc1-4987-9581-7f7d5246dd09.png)

**Comment by diabWH3** [comment]
I uninstalled the Android app, cleared the leftover cache, reinstalled it from the Play Store and still cannot access external URLs.

**Comment by diabWH3** [comment]
Hi Opee, have you had any chance to look at this still-ongoing issue? It hinders a LOT of the app's functionality for our kennel members. We still cannot do anything relating to external URLs: access original Facebook event page, navigate to trail using the Google Maps link, or pay for a trail via PayPal.

**Comment by James-A-White** [comment]
Reopened... will look into this ASAP

**Comment by diabWH3** [comment]
So, more interesting info....
Mexican Rimjob, who is one of my employees and is physically in the same building as me, tested the app on his Android phone (running the updated version of the HC app). He is a verified member of the SeaMon H3 kennel and cannot see the PayPal button for today's "Test #2" event. However, he can see the event and is also experiencing the same "external URL' issues as I am; he tried clicking the map location marker and it was unresponsive. 

Below are some screenshots: 
- The first from my phone, showing the test events and the PayPal button for "Test #2"
- The second from MRJ's phone, NOT showing the PayPal button
- The third confirming MRJ's "permanent member" status for SeaMon H3

![2022-01-07 - Screenshot DiaB](https://user-images.githubusercontent.com/49632769/148596597-2451092d-3453-4002-be82-863e728afee3.png)

![2022-01-07 - Screenshot MRJ](https://user-images.githubusercontent.com/49632769/148596625-f2c702a3-e4ec-433c-af8a-601b1c59ba97.png)

![Screenshot_20220107-112144](https://user-images.githubusercontent.com/49632769/148596643-aa608ad5-4153-4fb4-852c-cfad2c1d0b5f.png)

**Comment by James-A-White** [comment]
This issue was related to the Android version on the specific phone in use. My Android phone is older and did not exhibit this issue. Worked interactively with DIAB to troubleshoot. This is now fixed in 1.0.70 and will deploy this afternoon to the App stores.
